services:
  - type: web
    name: movie-night-api
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3